# Generated by Django 2.1.2 on 2020-03-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='room',
            name='poll_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='total_polls',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
